version: "3"

services: 
  server:
    container_name: server
    build: ./server

  nginx:
    container_name: nginx 
    image: nginx:latest
    ports:
      - "80:8080"
    volumes: 
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"